# Generated by Django 4.0.1 on 2022-02-23 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleo', models.CharField(max_length=100)),
                ('dirrecion', models.TextField(blank=True, null=True)),
                ('jornada', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_empleo', models.TextField()),
                ('acerca_de', models.TextField()),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('sitio', models.URLField(blank=True, null=True)),
                ('informacion', models.TextField()),
                ('dirrecion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_publicidad', models.CharField(max_length=100)),
                ('descripcion_publicidad', models.TextField()),
                ('eventos', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='Publicidad')),
                ('articulo', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('promocionado', models.BooleanField(default=True)),
                ('video', models.FileField(upload_to='Videos')),
                ('nombre_video', models.TextField()),
            ],
        ),
    ]
